# Prompt Engineering with Groq API LLMs — Hands-on Colab Exercise

This notebook covers:
- Zero-shot, one-shot, few-shot
- Role/persona prompting
- Instruction prompting
- Context-grounded prompting
- JSON / structured output prompting
- Classification, extraction, summarization, rewriting
- Reasoning-style prompting, step-back prompting
- Self-critique, prompt chaining, multi-turn prompting
- Rubric-based evaluation and prompt templates

In [1]:
print("Prompt Engineering with Groq API LLMs - Hands-on Colab Exercise")
print("We will test multiple prompt engineering techniques cell by cell.")

Prompt Engineering with Groq API LLMs - Hands-on Colab Exercise
We will test multiple prompt engineering techniques cell by cell.

In [2]:
!pip install -q groq pandas tabulate

In [3]:
import os
import json
import textwrap
import pandas as pd
from groq import Groq
from tabulate import tabulate

In [6]:
from dotenv import load_dotenv

load_dotenv()
client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

In [7]:
MODEL_NAME = "llama-3.3-70b-versatile"
print("Using model:", MODEL_NAME)

Using model: llama-3.3-70b-versatile

In [8]:
def ask_groq(prompt, system_prompt="You are a helpful AI assistant.", model=MODEL_NAME, temperature=0.3, max_tokens=1024):
    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

In [9]:
def show_result(title, prompt, response, width=110):
    print("="*120)
    print(f"TECHNIQUE: {title}")
    print("-"*120)
    print("PROMPT:")
    print(textwrap.fill(prompt, width=width))
    print("-"*120)
    print("MODEL RESPONSE:")
    print(response)
    print("="*120)

In [10]:
customer_feedback = """
I liked the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was damaged.
I may still recommend it because the discounts were attractive.
"""
print(customer_feedback)

I liked the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was damaged.
I may still recommend it because the discounts were attractive.

In [11]:
data = [
    {"feedback_id": 101, "feedback": "Checkout was fast and the UI is clean, but payment failed once and support was slow."},
    {"feedback_id": 102, "feedback": "Good product quality, nice discount, but damaged packaging and late delivery."},
    {"feedback_id": 103, "feedback": "The app is intuitive and easy to use. Customer support resolved my issue quickly."}
]
df = pd.DataFrame(data)
df

   feedback_id                                           feedback
0          101  Checkout was fast and the UI is clean, but pay...
1          102  Good product quality, nice discount, but damag...
2          103  The app is intuitive and easy to use. Customer...

In [12]:
prompt_zero_shot = f"""
Read the customer feedback below and identify:
1. Positive points
2. Negative points
3. Final customer sentiment as Positive / Neutral / Negative

Feedback:
{customer_feedback}
"""
response_zero_shot = ask_groq(prompt_zero_shot)
show_result("Zero-shot Prompting", prompt_zero_shot, response_zero_shot)

========================================================================================================================
TECHNIQUE: Zero-shot Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Read the customer feedback below and identify: 1. Positive points 2. Negative points 3. Final customer
sentiment as Positive / Neutral / Negative  Feedback:  I liked the app interface and the speed of checkout.
However, the payment page failed twice before succeeding. Customer support replied after 2 days, which is too
slow. Product quality was good overall, but delivery packaging was damaged. I may still recommend it because
the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Based on the customer feedback, here are the identified points:

1. **Positive points**:
   - The app interface was liked by the customer.
   - The speed of checkout was satisfactory.
   - Product quality was good overall.
   - Discounts were attractive.

2. **Negative points**:
   - The payment page failed twice before succeeding, indicating a technical issue.
   - Customer support replied after 2 days, which the customer considered too slow.
   - Delivery packaging was damaged.

3. **Final customer sentiment**: Neutral

The customer had both positive and negative experiences. While they liked certain aspects of the service (interface, checkout speed, product quality, discounts), they also faced significant issues (payment failure, slow customer support, damaged packaging). The customer mentions they "may still recommend it," indicating that their overall sentiment is not entirely positive or negative, but rather neutral, as they weigh the pros and cons of their experience.
========================================================================================================================

In [13]:
prompt_one_shot = f"""
Example:
Feedback: "The app design is nice but delivery was late."
Output:
Positive points: app design
Negative points: late delivery
Sentiment: Neutral

Now do the same for the feedback below.

Feedback:
{customer_feedback}
"""
response_one_shot = ask_groq(prompt_one_shot)
show_result("One-shot Prompting", prompt_one_shot, response_one_shot)

========================================================================================================================
TECHNIQUE: One-shot Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Example: Feedback: "The app design is nice but delivery was late." Output: Positive points: app design
Negative points: late delivery Sentiment: Neutral  Now do the same for the feedback below.  Feedback:  I liked
the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery
packaging was damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here's the analysis of the feedback:

Positive points:
- app interface
- speed of checkout
- product quality
- attractive discounts

Negative points:
- payment page failed twice
- slow customer support response (after 2 days)
- damaged delivery packaging

Sentiment: Neutral
========================================================================================================================

In [14]:
prompt_few_shot = f"""
You are analyzing e-commerce customer feedback.

Example 1:
Feedback: "The product quality is excellent but shipping was delayed."
Output:
Positive points: product quality
Negative points: delayed shipping
Sentiment: Neutral

Example 2:
Feedback: "Support was quick, refund was smooth, and the app was easy to use."
Output:
Positive points: quick support, smooth refund, easy app usage
Negative points: none
Sentiment: Positive

Example 3:
Feedback: "Payment failed twice and the package arrived broken."
Output:
Positive points: none
Negative points: payment failure, damaged package
Sentiment: Negative

Now analyze this feedback:

Feedback:
{customer_feedback}
"""
response_few_shot = ask_groq(prompt_few_shot)
show_result("Few-shot Prompting", prompt_few_shot, response_few_shot)

========================================================================================================================
TECHNIQUE: Few-shot Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 You are analyzing e-commerce customer feedback.  Example 1: Feedback: "The product quality is excellent but
shipping was delayed." Output: Positive points: product quality Negative points: delayed shipping Sentiment:
Neutral  Example 2: Feedback: "Support was quick, refund was smooth, and the app was easy to use." Output:
Positive points: quick support, smooth refund, easy app usage Negative points: none Sentiment: Positive
Example 3: Feedback: "Payment failed twice and the package arrived broken." Output: Positive points: none
Negative points: payment failure, damaged package Sentiment: Negative  Now analyze this feedback:  Feedback:
I liked the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery
packaging was damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Let's analyze the given feedback:

Feedback: "I liked the app interface and the speed of checkout. However, the payment page failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was damaged. I may still recommend it because the discounts were attractive."

Output:
Positive points:
- app interface
- speed of checkout
- product quality
- attractive discounts

Negative points:
- payment page failure
- slow customer support
- damaged delivery packaging

Sentiment: Neutral

The customer has mentioned both positive and negative aspects of their experience. Although they faced some issues, they seem to be somewhat satisfied due to the attractive discounts and overall product quality, which is why the sentiment is neutral rather than entirely positive or negative.
========================================================================================================================

In [15]:
prompt_role = f"""
You are a senior Customer Experience Analyst in an e-commerce company.
Analyze the feedback and provide:
1. Customer pain points
2. Business risks
3. Improvement recommendations

Feedback:
{customer_feedback}
"""
response_role = ask_groq(prompt_role)
show_result("Role / Persona Prompting", prompt_role, response_role)

========================================================================================================================
TECHNIQUE: Role / Persona Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 You are a senior Customer Experience Analyst in an e-commerce company. Analyze the feedback and provide: 1.
Customer pain points 2. Business risks 3. Improvement recommendations  Feedback:  I liked the app interface
and the speed of checkout. However, the payment page failed twice before succeeding. Customer support replied
after 2 days, which is too slow. Product quality was good overall, but delivery packaging was damaged. I may
still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**Analysis of Customer Feedback**

### 1. Customer Pain Points:

- **Technical Issues:** The customer experienced difficulties with the payment page, which failed twice before the transaction was successfully completed. This indicates a need for improvement in the reliability and stability of the payment processing system.
- **Slow Customer Support:** The customer had to wait 2 days for a response from customer support, which was perceived as too slow. This suggests that the current response time does not meet customer expectations for timely assistance.
- **Damaged Delivery Packaging:** The packaging of the delivered product was damaged, although the product quality itself was good. This points to a need for better packaging to prevent damage during shipping.

### 2. Business Risks:

- **Loss of Customer Loyalty:** The technical issues and slow customer support may lead to a decrease in customer loyalty. If not addressed, these problems could result in customers seeking alternative platforms for their shopping needs.
- **Negative Word-of-Mouth:** Despite the customer mentioning they might still recommend the app, the overall experience was marred by significant issues. If these issues persist, they could lead to negative reviews and word-of-mouth, potentially deterring new customers.
- **Reputation Damage:** Continuous problems with payment processing, customer support, and packaging could damage the company's reputation, making it less competitive in the e-commerce market.

### 3. Improvement Recommendations:

- **Enhance Payment Processing System:** Invest in upgrading the payment page to make it more reliable and efficient. This could involve integrating multiple payment options, improving server capacity to handle high volumes of transactions, and implementing a more robust error handling system to minimize failures.
- **Streamline Customer Support:** Implement a system that allows for quicker response times, such as using AI-powered chatbots for initial inquiries, hiring more support staff, or adopting a 24/7 support model. Aim for response times that are significantly less than 2 days, ideally within a few hours.
- **Improve Packaging Quality:** Review and enhance the packaging materials and methods used for shipping products. This could involve using more durable materials, better sizing of boxes to fit products snugly, and possibly adding extra protection for fragile items. Conduct regular quality checks on outgoing packages to ensure they meet high standards.
- **Proactive Communication:** Consider proactive communication with customers about any issues they might be experiencing, such as immediate notification if a payment fails and an estimated time for resolution. This can help manage expectations and show that the company is actively working to resolve problems.
- **Discounts and Loyalty Programs:** Continue to offer attractive discounts and consider implementing a loyalty program to incentivize repeat business and improve customer retention, especially for customers who have experienced issues but are willing to give the company another chance.
========================================================================================================================

In [16]:
prompt_instruction = f"""
Task: Analyze the feedback.

Rules:
- Use bullet points
- Keep each bullet under 15 words
- Separate positives, negatives, sentiment, and action items
- Do not add information not present in the feedback

Feedback:
{customer_feedback}
"""
response_instruction = ask_groq(prompt_instruction)
show_result("Instruction-based Prompting", prompt_instruction, response_instruction)

========================================================================================================================
TECHNIQUE: Instruction-based Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Task: Analyze the feedback.  Rules: - Use bullet points - Keep each bullet under 15 words - Separate
positives, negatives, sentiment, and action items - Do not add information not present in the feedback
Feedback:  I liked the app interface and the speed of checkout. However, the payment page failed twice before
succeeding. Customer support replied after 2 days, which is too slow. Product quality was good overall, but
delivery packaging was damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**Positives:**
* Liked app interface
* Fast checkout
* Good product quality
* Attractive discounts

**Negatives:**
* Payment page failed
* Slow support reply
* Damaged packaging

**Sentiment:**
* Generally positive
* Frustrated with support

**Action Items:**
* Fix payment page
* Improve support reply time
* Improve packaging
========================================================================================================================

In [17]:
prompt_context = f"""
Context:
You are working for an e-commerce platform whose priorities are:
1. Reduce payment failures
2. Improve customer support turnaround time
3. Reduce packaging damage complaints

Task:
Analyze the feedback in the context of these business priorities and rank the top 3 issues.

Feedback:
{customer_feedback}
"""
response_context = ask_groq(prompt_context)
show_result("Context-grounded Prompting", prompt_context, response_context)

========================================================================================================================
TECHNIQUE: Context-grounded Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Context: You are working for an e-commerce platform whose priorities are: 1. Reduce payment failures 2.
Improve customer support turnaround time 3. Reduce packaging damage complaints  Task: Analyze the feedback in
the context of these business priorities and rank the top 3 issues.  Feedback:  I liked the app interface and
the speed of checkout. However, the payment page failed twice before succeeding. Customer support replied
after 2 days, which is too slow. Product quality was good overall, but delivery packaging was damaged. I may
still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Based on the provided feedback, I've analyzed the issues in the context of the e-commerce platform's priorities. Here are the top 3 issues ranked:

1. **Payment failures**: The customer experienced payment failures twice before succeeding, which directly relates to the platform's priority of reducing payment failures. This issue needs to be addressed to improve the overall checkout experience.
2. **Slow customer support turnaround time**: The customer had to wait 2 days for a response from customer support, which is deemed too slow. This aligns with the platform's priority of improving customer support turnaround time. Faster response times can help resolve issues promptly and enhance customer satisfaction.
3. **Packaging damage complaints**: The customer received a damaged delivery package, which is a concern that needs to be addressed to reduce packaging damage complaints. Although the product quality was good, the damaged packaging may still impact the customer's overall experience and perception of the platform.

These top 3 issues are directly related to the platform's priorities and should be addressed to improve the customer experience and overall satisfaction.
========================================================================================================================

In [19]:
prompt_json = f"""
Analyze the customer feedback and return output in valid JSON only.

Required schema:
{{
  "positive_points": [],
  "negative_points": [],
  "sentiment": "",
  "recommendation_priority": []
}}

Customer Feedback:
{customer_feedback}
"""
response_json = ask_groq(prompt_json)
show_result("Structured / JSON Output Prompting", prompt_json, response_json)

========================================================================================================================
TECHNIQUE: Structured / JSON Output Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Analyze the customer feedback and return output in valid JSON only.  Required schema: {   "positive_points":
[],   "negative_points": [],   "sentiment": "",   "recommendation_priority": [] }  Customer Feedback:  I liked
the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery
packaging was damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
```
{
  "positive_points": [
    "app interface",
    "speed of checkout",
    "product quality",
    "discounts"
  ],
  "negative_points": [
    "payment page issues",
    "slow customer support response",
    "damaged delivery packaging"
  ],
  "sentiment": "neutral",
  "recommendation_priority": [
    "improve payment page functionality",
    "enhance customer support response time",
    "ensure proper delivery packaging"
  ]
}
```
========================================================================================================================

In [20]:
try:
    parsed = json.loads(response_json)
    print(json.dumps(parsed, indent=2))
except Exception as e:
    print("JSON parsing failed:", e)
    print("Raw output:")
    print(response_json)

JSON parsing failed: Expecting value: line 1 column 1 (char 0)
Raw output:
```
{
  "positive_points": [
    "app interface",
    "speed of checkout",
    "product quality",
    "discounts"
  ],
  "negative_points": [
    "payment page issues",
    "slow customer support response",
    "damaged delivery packaging"
  ],
  "sentiment": "neutral",
  "recommendation_priority": [
    "improve payment page functionality",
    "enhance customer support response time",
    "ensure proper delivery packaging"
  ]
}
```

In [21]:
prompt_classification = f"""
Classify the feedback into one of these categories:
- Product Issue
- Delivery Issue
- Support Issue
- Payment Issue
- UX/UI Praise
- Mixed Experience

Return:
1. Primary category
2. Secondary category if any
3. Reason in 2 lines

Feedback:
{customer_feedback}
"""
response_classification = ask_groq(prompt_classification)
show_result("Classification Prompting", prompt_classification, response_classification)

========================================================================================================================
TECHNIQUE: Classification Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Classify the feedback into one of these categories: - Product Issue - Delivery Issue - Support Issue -
Payment Issue - UX/UI Praise - Mixed Experience  Return: 1. Primary category 2. Secondary category if any 3.
Reason in 2 lines  Feedback:  I liked the app interface and the speed of checkout. However, the payment page
failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product quality was
good overall, but delivery packaging was damaged. I may still recommend it because the discounts were
attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
1. Mixed Experience
2. Payment Issue, Support Issue, Delivery Issue
3. The customer had both positive and negative experiences, including issues with payment, support, and delivery, but also liked the app interface and product quality. Despite the problems, they might still recommend the service due to attractive discounts.
========================================================================================================================

In [22]:
prompt_extraction = f"""
Extract the following from the feedback:
- product_quality_issue: yes/no
- delivery_issue: yes/no
- support_issue: yes/no
- payment_issue: yes/no
- discount_mentioned: yes/no
- recommendation_intent: yes/no

Feedback:
{customer_feedback}

Return only JSON.
"""
response_extraction = ask_groq(prompt_extraction)
show_result("Information Extraction Prompting", prompt_extraction, response_extraction)

========================================================================================================================
TECHNIQUE: Information Extraction Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Extract the following from the feedback: - product_quality_issue: yes/no - delivery_issue: yes/no -
support_issue: yes/no - payment_issue: yes/no - discount_mentioned: yes/no - recommendation_intent: yes/no
Feedback:  I liked the app interface and the speed of checkout. However, the payment page failed twice before
succeeding. Customer support replied after 2 days, which is too slow. Product quality was good overall, but
delivery packaging was damaged. I may still recommend it because the discounts were attractive.   Return only
JSON.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
```json
{
  "product_quality_issue": "no",
  "delivery_issue": "yes",
  "support_issue": "yes",
  "payment_issue": "yes",
  "discount_mentioned": "yes",
  "recommendation_intent": "yes"
}
```
========================================================================================================================

In [23]:
prompt_summary = f"""
Summarize the feedback in:
1. 1 sentence
2. 3 bullet points
3. an executive summary under 50 words

Feedback:
{customer_feedback}
"""
response_summary = ask_groq(prompt_summary)
show_result("Summarization Prompting", prompt_summary, response_summary)

========================================================================================================================
TECHNIQUE: Summarization Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Summarize the feedback in: 1. 1 sentence 2. 3 bullet points 3. an executive summary under 50 words  Feedback:
I liked the app interface and the speed of checkout. However, the payment page failed twice before succeeding.
Customer support replied after 2 days, which is too slow. Product quality was good overall, but delivery
packaging was damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are the summaries:

1. The customer had a mixed experience with the app, citing both positive and negative aspects, including a faulty payment page and slow customer support.
2. Here are the key points:
* The app interface and checkout speed were satisfactory
* The payment page experienced technical issues, and customer support was slow to respond
* Product quality was good, but delivery packaging was damaged
3. Mixed review: good app, slow support, damaged packaging.
========================================================================================================================

In [24]:
prompt_rewrite = f"""
Rewrite the following feedback into:
1. A professional escalation email to the operations team
2. A concise CRM note
3. A tweet-sized summary

Feedback:
{customer_feedback}
"""
response_rewrite = ask_groq(prompt_rewrite)
show_result("Transformation / Rewriting Prompting", prompt_rewrite, response_rewrite)

========================================================================================================================
TECHNIQUE: Transformation / Rewriting Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Rewrite the following feedback into: 1. A professional escalation email to the operations team 2. A concise
CRM note 3. A tweet-sized summary  Feedback:  I liked the app interface and the speed of checkout. However,
the payment page failed twice before succeeding. Customer support replied after 2 days, which is too slow.
Product quality was good overall, but delivery packaging was damaged. I may still recommend it because the
discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are the rewritten feedback in the requested formats:

**1. Professional Escalation Email to the Operations Team:**

Subject: Escalation: Payment Page Issues, Delayed Customer Support, and Damaged Packaging

Dear Operations Team,

I am writing to bring to your attention a recent customer experience that requires immediate attention. The customer reported a smooth app interface and checkout process, but encountered issues with the payment page, which failed twice before succeeding. Furthermore, the customer had to wait 2 days for a response from our customer support team, which is below our expected standards.

Additionally, the customer received their product with damaged packaging, despite the product quality being satisfactory. The customer was satisfied with the discounts offered, but these issues may impact their decision to recommend our service to others.

I kindly request that you investigate these matters and take necessary steps to:

* Resolve the payment page issues to prevent future failures
* Improve customer support response times to meet our expected standards
* Enhance packaging quality to prevent damage during delivery

Please provide an update on the actions taken to address these concerns.

Best regards,
[Your Name]

**2. Concise CRM Note:**

"Customer experienced payment page issues, delayed support response (2 days), and damaged packaging. Product quality and discounts were satisfactory. May still recommend despite issues."

**3. Tweet-sized Summary:**

"Recent experience: smooth app & checkout, but payment page failed twice, slow support response, and damaged packaging. Good product quality & discounts, but room for improvement #customerexperience #feedback"
========================================================================================================================

In [25]:
prompt_reasoning = f"""
Analyze the customer feedback step by step.

Return:
1. Key observations
2. How you inferred sentiment
3. Final conclusion

Keep reasoning concise and task-focused.

Feedback:
{customer_feedback}
"""
response_reasoning = ask_groq(prompt_reasoning)
show_result("Reasoning-style Prompting", prompt_reasoning, response_reasoning)

========================================================================================================================
TECHNIQUE: Reasoning-style Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Analyze the customer feedback step by step.  Return: 1. Key observations 2. How you inferred sentiment 3.
Final conclusion  Keep reasoning concise and task-focused.  Feedback:  I liked the app interface and the speed
of checkout. However, the payment page failed twice before succeeding. Customer support replied after 2 days,
which is too slow. Product quality was good overall, but delivery packaging was damaged. I may still recommend
it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here's the analysis of the customer feedback:

1. **Key observations**:
   - The customer liked the app interface and checkout speed.
   - The payment page had issues, failing twice before succeeding.
   - Customer support response was slow (2 days).
   - Product quality was good, but delivery packaging was damaged.
   - Discounts were attractive.

2. **How sentiment was inferred**:
   - Positive sentiment: The customer liked the app interface, checkout speed, product quality, and found the discounts attractive.
   - Negative sentiment: The customer experienced issues with the payment page, slow customer support response, and damaged delivery packaging.

3. **Final conclusion**:
   - The customer had mixed feelings about their experience. While they appreciated certain aspects like the interface and discounts, they were dissatisfied with the payment process, customer support, and packaging. Despite this, they might still recommend the service due to the attractive discounts, indicating a somewhat positive overall sentiment.
========================================================================================================================

In [26]:
prompt_step_back = f"""
Before analyzing the feedback, first answer:
"What are the common dimensions used to evaluate customer feedback in e-commerce?"

Then use those dimensions to analyze the following feedback:
{customer_feedback}

Return:
1. General evaluation dimensions
2. Feedback analysis using those dimensions
"""
response_step_back = ask_groq(prompt_step_back)
show_result("Step-back Prompting", prompt_step_back, response_step_back)

========================================================================================================================
TECHNIQUE: Step-back Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Before analyzing the feedback, first answer: "What are the common dimensions used to evaluate customer
feedback in e-commerce?"  Then use those dimensions to analyze the following feedback:  I liked the app
interface and the speed of checkout. However, the payment page failed twice before succeeding. Customer
support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was
damaged. I may still recommend it because the discounts were attractive.   Return: 1. General evaluation
dimensions 2. Feedback analysis using those dimensions
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**1. General evaluation dimensions:**
The common dimensions used to evaluate customer feedback in e-commerce include:
- **User Experience (UX)**: This encompasses the overall experience a customer has while interacting with the website or app, including navigation, search functionality, and checkout process.
- **Customer Support**: This dimension evaluates the responsiveness, helpfulness, and resolution time of the support team.
- **Product Quality**: This assesses the quality, durability, and performance of the products purchased.
- **Delivery and Logistics**: This includes the speed of delivery, packaging quality, and the condition of the products upon arrival.
- **Value for Money**: This dimension considers whether the customer feels they received a good value for the price paid, including the attractiveness of discounts and promotions.

**2. Feedback analysis using those dimensions:**
Analyzing the given feedback using the above dimensions:
- **User Experience (UX)**: The customer liked the app interface and the speed of checkout, indicating a positive user experience. However, the payment page failing twice before succeeding is a significant negative aspect, suggesting room for improvement in terms of reliability and smoothness of the transaction process.
- **Customer Support**: The customer support replied after 2 days, which the customer found too slow. This indicates a need for improvement in the responsiveness of the customer support team.
- **Product Quality**: The customer mentioned that the product quality was good overall, which is a positive note. However, the delivery packaging was damaged, suggesting an issue with the handling or packaging process rather than the product itself.
- **Delivery and Logistics**: The fact that the delivery packaging was damaged is a negative aspect, indicating potential issues with the logistics or handling of shipments.
- **Value for Money**: The customer found the discounts attractive, which suggests that they felt they were getting a good value for their money. This, combined with the overall good product quality, might encourage the customer to recommend the service despite the other issues encountered.

Overall, while the customer had some positive experiences, such as liking the app interface and finding the discounts attractive, there were significant negative aspects, including issues with the payment process, slow customer support, and damaged delivery packaging. Addressing these issues could significantly improve customer satisfaction and loyalty.
========================================================================================================================

In [27]:
initial_prompt = f"""
Analyze the feedback and provide positives, negatives, sentiment, and action items.

Feedback:
{customer_feedback}
"""
initial_response = ask_groq(initial_prompt)

critique_prompt = f"""
You previously generated the following analysis:

{initial_response}

Now critique it for:
1. Missing points
2. Overstatements
3. Weak recommendations
4. Better final version

Original feedback:
{customer_feedback}
"""
critique_response = ask_groq(critique_prompt)
show_result("Initial Analysis", initial_prompt, initial_response)
show_result("Self-reflection / Critique Prompting", critique_prompt, critique_response)

========================================================================================================================
TECHNIQUE: Initial Analysis
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Analyze the feedback and provide positives, negatives, sentiment, and action items.  Feedback:  I liked the
app interface and the speed of checkout. However, the payment page failed twice before succeeding. Customer
support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was
damaged. I may still recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**Analysis of Feedback**

**Positives:**

1. The app interface was liked by the customer, indicating a user-friendly design.
2. The speed of checkout was appreciated, suggesting a smooth and efficient payment process.
3. The product quality was good overall, indicating that the customer was satisfied with the items received.
4. The discounts offered were attractive, which was a major incentive for the customer.

**Negatives:**

1. The payment page failed twice before succeeding, causing frustration and inconvenience.
2. Customer support replied after 2 days, which was considered too slow and may have exacerbated the customer's frustration.
3. The delivery packaging was damaged, which may have put the products at risk of damage during transit.

**Sentiment:**
The overall sentiment of the feedback is neutral, with both positive and negative experiences mentioned. The customer had some issues with the payment process and customer support, but was satisfied with the product quality and discounts.

**Action Items:**

1. **Improve payment page stability**: Investigate and resolve the issue with the payment page to prevent future failures and ensure a seamless checkout experience.
2. **Enhance customer support response time**: Implement measures to reduce the response time of customer support, such as increasing staff or implementing automated support systems.
3. **Improve delivery packaging**: Review and improve packaging materials and procedures to prevent damage during transit and ensure that products arrive in good condition.
4. **Monitor and maintain product quality**: Continue to ensure that product quality meets customer expectations to maintain customer satisfaction and loyalty.
5. **Consider proactive communication**: Consider proactively communicating with customers about any issues or delays to manage expectations and prevent frustration.
========================================================================================================================
========================================================================================================================
TECHNIQUE: Self-reflection / Critique Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 You previously generated the following analysis:  **Analysis of Feedback**  **Positives:**  1. The app
interface was liked by the customer, indicating a user-friendly design. 2. The speed of checkout was
appreciated, suggesting a smooth and efficient payment process. 3. The product quality was good overall,
indicating that the customer was satisfied with the items received. 4. The discounts offered were attractive,
which was a major incentive for the customer.  **Negatives:**  1. The payment page failed twice before
succeeding, causing frustration and inconvenience. 2. Customer support replied after 2 days, which was
considered too slow and may have exacerbated the customer's frustration. 3. The delivery packaging was
damaged, which may have put the products at risk of damage during transit.  **Sentiment:** The overall
sentiment of the feedback is neutral, with both positive and negative experiences mentioned. The customer had
some issues with the payment process and customer support, but was satisfied with the product quality and
discounts.  **Action Items:**  1. **Improve payment page stability**: Investigate and resolve the issue with
the payment page to prevent future failures and ensure a seamless checkout experience. 2. **Enhance customer
support response time**: Implement measures to reduce the response time of customer support, such as
increasing staff or implementing automated support systems. 3. **Improve delivery packaging**: Review and
improve packaging materials and procedures to prevent damage during transit and ensure that products arrive in
good condition. 4. **Monitor and maintain product quality**: Continue to ensure that product quality meets
customer expectations to maintain customer satisfaction and loyalty. 5. **Consider proactive communication**:
Consider proactively communicating with customers about any issues or delays to manage expectations and
prevent frustration.  Now critique it for: 1. Missing points 2. Overstatements 3. Weak recommendations 4.
Better final version  Original feedback:  I liked the app interface and the speed of checkout. However, the
payment page failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product
quality was good overall, but delivery packaging was damaged. I may still recommend it because the discounts
were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**Critique of the Analysis**

### Missing Points

1. **Customer's intention to recommend**: The analysis mentions that the customer "may still recommend" the app, but it doesn't explore this point further. It would be useful to discuss how the customer's experience might impact their decision to recommend the app to others.
2. **Emotional impact**: The analysis focuses on the factual aspects of the customer's experience but doesn't consider the emotional impact of the issues they encountered. For example, how did the payment page failures and slow customer support response time affect the customer's frustration levels and overall satisfaction?
3. **Comparison to expectations**: The analysis doesn't discuss how the customer's experience compared to their initial expectations. Were there any specific expectations that were met or unmet, and how did this impact their overall satisfaction?

### Overstatements

1. **Payment page stability**: The analysis states that the payment page "failed twice before succeeding," which is a significant issue. However, it's not clear if this is a common problem or an isolated incident. The recommendation to "improve payment page stability" might be an overstatement if this is a rare occurrence.
2. **Customer support response time**: The analysis states that the customer support response time was "too slow," but it's not clear what the customer's expectations were. Was the customer expecting a response within a certain timeframe (e.g., 24 hours), or were they surprised by the 2-day delay?

### Weak Recommendations

1. **Improve payment page stability**: The recommendation to "investigate and resolve the issue" is vague and doesn't provide specific guidance on how to address the problem. A stronger recommendation might include suggestions for testing and quality assurance to prevent similar issues in the future.
2. **Enhance customer support response time**: The recommendation to "implement measures to reduce response time" is also vague and doesn't provide specific guidance on how to achieve this goal. A stronger recommendation might include suggestions for increasing staff, implementing automated support systems, or setting clear response time targets.

### Better Final Version

Here's an updated version of the analysis that addresses the missing points, overstatements, and weak recommendations:

**Analysis of Feedback**

**Positives:**

1. The app interface was liked by the customer, indicating a user-friendly design.
2. The speed of checkout was appreciated, suggesting a smooth and efficient payment process.
3. The product quality was good overall, indicating that the customer was satisfied with the items received.
4. The discounts offered were attractive, which was a major incentive for the customer.

**Negatives:**

1. The payment page failed twice before succeeding, causing frustration and inconvenience.
2. Customer support replied after 2 days, which was slower than expected and may have exacerbated the customer's frustration.
3. The delivery packaging was damaged, which may have put the products at risk of damage during transit.

**Sentiment:**
The overall sentiment of the feedback is neutral, with both positive and negative experiences mentioned. The customer had some issues with the payment process and customer support, but was satisfied with the product quality and discounts.

**Action Items:**

1. **Investigate payment page issues**: Conduct thorough testing and quality assurance to identify and resolve the issue with the payment page, and implement measures to prevent similar failures in the future.
2. **Set clear customer support response time targets**: Establish clear response time targets for customer support (e.g., 24 hours) and implement measures to achieve these targets, such as increasing staff or implementing automated support systems.
3. **Improve delivery packaging**: Review and improve packaging materials and procedures to prevent damage during transit and ensure that products arrive in good condition.
4. **Monitor and maintain product quality**: Continue to ensure that product quality meets customer expectations to maintain customer satisfaction and loyalty.
5. **Proactively communicate with customers**: Consider proactively communicating with customers about any issues or delays to manage expectations and prevent frustration.
6. **Gather more feedback**: Collect more feedback from customers to understand their expectations and experiences, and use this information to identify areas for improvement.

This updated version of the analysis provides more specific and actionable recommendations, and addresses the missing points and overstatements in the original analysis.
========================================================================================================================

In [28]:
prompt_chain_1 = f"""
Extract all issues mentioned in the feedback as a bullet list.

Feedback:
{customer_feedback}
"""
issues_output = ask_groq(prompt_chain_1)
show_result("Prompt Chaining - Stage 1", prompt_chain_1, issues_output)

========================================================================================================================
TECHNIQUE: Prompt Chaining - Stage 1
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Extract all issues mentioned in the feedback as a bullet list.  Feedback:  I liked the app interface and the
speed of checkout. However, the payment page failed twice before succeeding. Customer support replied after 2
days, which is too slow. Product quality was good overall, but delivery packaging was damaged. I may still
recommend it because the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are the issues mentioned in the feedback as a bullet list:

* The payment page failed twice before succeeding
* Customer support replied too slowly (after 2 days)
* Delivery packaging was damaged
========================================================================================================================

In [29]:
prompt_chain_2 = f"""
Given these extracted issues:
{issues_output}

Rank them by business severity from highest to lowest.
Explain each ranking in one line.
"""
priority_output = ask_groq(prompt_chain_2)
show_result("Prompt Chaining - Stage 2", prompt_chain_2, priority_output)

========================================================================================================================
TECHNIQUE: Prompt Chaining - Stage 2
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Given these extracted issues: Here are the issues mentioned in the feedback as a bullet list:  * The payment
page failed twice before succeeding * Customer support replied too slowly (after 2 days) * Delivery packaging
was damaged  Rank them by business severity from highest to lowest. Explain each ranking in one line.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are the issues ranked by business severity from highest to lowest:
1. The payment page failed twice before succeeding - This issue has the highest severity as it directly affects revenue and can lead to lost sales.
2. Customer support replied too slowly (after 2 days) - This issue has moderate severity as delayed support can erode customer trust and loyalty.
3. Delivery packaging was damaged - This issue has the lowest severity as it is a relatively minor problem that can be easily resolved through replacement or refund, without significant long-term impact.
========================================================================================================================

In [30]:
prompt_chain_3 = f"""
Using this prioritized issue list:
{priority_output}

Create a 30-day action plan for the operations team.
"""
action_plan_output = ask_groq(prompt_chain_3)
show_result("Prompt Chaining - Stage 3", prompt_chain_3, action_plan_output)

========================================================================================================================
TECHNIQUE: Prompt Chaining - Stage 3
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Using this prioritized issue list: Here are the issues ranked by business severity from highest to lowest: 1.
The payment page failed twice before succeeding - This issue has the highest severity as it directly affects
revenue and can lead to lost sales. 2. Customer support replied too slowly (after 2 days) - This issue has
moderate severity as delayed support can erode customer trust and loyalty. 3. Delivery packaging was damaged -
This issue has the lowest severity as it is a relatively minor problem that can be easily resolved through
replacement or refund, without significant long-term impact.  Create a 30-day action plan for the operations
team.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**30-Day Action Plan for Operations Team**

**Week 1 (Days 1-7): High Severity Issue - Payment Page Failure**

1. **Day 1-2**: Investigate the root cause of the payment page failure and identify the technical issues.
2. **Day 3-4**: Collaborate with the development team to implement a fix for the payment page issue.
3. **Day 5-6**: Conduct thorough testing to ensure the payment page is functioning correctly.
4. **Day 7**: Deploy the updated payment page and monitor its performance.

**Week 2 (Days 8-14): Moderate Severity Issue - Customer Support Response Time**

1. **Day 8-9**: Analyze the current customer support process and identify bottlenecks.
2. **Day 10-11**: Develop a plan to increase customer support staff or implement automated response systems to reduce response time.
3. **Day 12-13**: Implement the plan and provide training to customer support staff on new procedures.
4. **Day 14**: Monitor customer support response time and adjust the plan as needed.

**Week 3-4 (Days 15-30): Low Severity Issue - Delivery Packaging Damage**

1. **Day 15-16**: Investigate the cause of damaged delivery packaging and identify areas for improvement.
2. **Day 17-18**: Collaborate with the logistics team to implement changes to packaging procedures.
3. **Day 19-20**: Develop a plan to inspect and replace damaged packaging materials.
4. **Day 21-30**: Monitor packaging damage rates and continue to refine the packaging process.

**Additional Tasks**

1. **Day 1-30**: Continuously monitor the payment page, customer support response time, and packaging damage rates to ensure issues are resolved and do not recur.
2. **Day 15 and 30**: Conduct review meetings with the operations team to discuss progress, address any new issues, and adjust the action plan as needed.

By following this 30-day action plan, the operations team can effectively address the prioritized issues, improve the overall customer experience, and minimize the risk of lost sales and eroded customer trust.
========================================================================================================================

In [31]:
def chat_groq(messages, model=MODEL_NAME, temperature=0.3, max_tokens=1024):
    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=messages
    )
    return response.choices[0].message.content

In [32]:
messages = [
    {"role": "system", "content": "You are a customer feedback analyst."},
    {"role": "user", "content": f"Analyze this feedback:\n{customer_feedback}"}
]

resp1 = chat_groq(messages)
print("Assistant:", resp1)

messages.append({"role": "assistant", "content": resp1})
messages.append({"role": "user", "content": "Now convert that into a priority matrix with High / Medium / Low severity."})

resp2 = chat_groq(messages)
print("\nAssistant Follow-up:\n", resp2)

Assistant: **Summary:**
The customer had a mixed experience with the app. They liked the interface and checkout speed, but encountered issues with the payment page and customer support response time. The product quality was good, but the delivery packaging was damaged. Despite these issues, the customer might still recommend the app due to attractive discounts.

**Key Strengths:**

1. **App Interface**: The customer liked the app's interface, indicating a well-designed and user-friendly experience.
2. **Checkout Speed**: The checkout process was fast, which is a significant factor in ensuring a smooth customer experience.
3. **Product Quality**: The customer was satisfied with the overall quality of the product.
4. **Discounts**: The attractive discounts offered by the app were a major draw for the customer.

**Key Areas for Improvement:**

1. **Payment Page**: The payment page failed twice before succeeding, which can be frustrating and may lead to abandoned transactions.
2. **Customer Support Response Time**: The customer support team took 2 days to respond, which is too slow and may lead to customer dissatisfaction.
3. **Delivery Packaging**: The damaged packaging is a concern, as it may affect the customer's perception of the company's attention to detail and care for their products.

**Recommendations:**

1. **Optimize Payment Page**: Ensure that the payment page is stable and secure to prevent failures and minimize frustration.
2. **Improve Customer Support Response Time**: Aim to respond to customer inquiries within a few hours or at least within 24 hours to demonstrate a commitment to customer satisfaction.
3. **Enhance Delivery Packaging**: Review and improve packaging materials and processes to prevent damage during shipping and ensure that products arrive in good condition.

By addressing these areas for improvement, the company can enhance the overall customer experience, increase satisfaction, and encourage positive word-of-mouth and recommendations.

Assistant Follow-up:
 **Priority Matrix:**

| Issue | Description | Severity | Recommendation |
| --- | --- | --- | --- |
| 1. Payment Page Failures | Payment page failed twice before succeeding | **High** | Optimize payment page to prevent failures and minimize frustration |
| 2. Slow Customer Support Response | Customer support replied after 2 days | **High** | Improve customer support response time to within 24 hours |
| 3. Damaged Delivery Packaging | Delivery packaging was damaged | **Medium** | Enhance delivery packaging materials and processes to prevent damage |
| 4. App Interface and Checkout Speed | Customer liked the app interface and checkout speed | **Low** | Continue to maintain and improve app interface and checkout speed |
| 5. Product Quality | Product quality was good overall | **Low** | Continue to maintain high product quality standards |
| 6. Attractive Discounts | Discounts were attractive | **Low** | Continue to offer competitive discounts and promotions |

**Severity Criteria:**

* **High**: Issues that significantly impact customer experience, lead to frustration, or result in lost sales (e.g., payment page failures, slow customer support response).
* **Medium**: Issues that moderately impact customer experience or may lead to some dissatisfaction (e.g., damaged delivery packaging).
* **Low**: Issues that have a minimal impact on customer experience or are already being done well (e.g., app interface, product quality, attractive discounts).

By prioritizing the issues based on severity, the company can focus on addressing the most critical problems first (payment page failures and slow customer support response) and then move on to the medium and low-severity issues.

In [33]:
candidate_answer = """
Positive points: app UI, checkout speed, discounts
Negative points: payment page failed, support was slow, packaging damaged
Sentiment: Neutral
"""

prompt_eval = f"""
Evaluate the following answer on a scale of 1 to 5 for each criterion:
- Completeness
- Accuracy
- Relevance
- Clarity

Also provide:
- total score /20
- 3 improvement suggestions

Original feedback:
{customer_feedback}

Candidate answer:
{candidate_answer}
"""
response_eval = ask_groq(prompt_eval)
show_result("Rubric-based Evaluation Prompting", prompt_eval, response_eval)

========================================================================================================================
TECHNIQUE: Rubric-based Evaluation Prompting
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Evaluate the following answer on a scale of 1 to 5 for each criterion: - Completeness - Accuracy - Relevance
- Clarity  Also provide: - total score /20 - 3 improvement suggestions  Original feedback:  I liked the app
interface and the speed of checkout. However, the payment page failed twice before succeeding. Customer
support replied after 2 days, which is too slow. Product quality was good overall, but delivery packaging was
damaged. I may still recommend it because the discounts were attractive.   Candidate answer:  Positive points:
app UI, checkout speed, discounts Negative points: payment page failed, support was slow, packaging damaged
Sentiment: Neutral
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here's the evaluation of the candidate answer:

* Completeness: 3 (The answer provides a brief summary of the positive and negative points, but it lacks details and specific examples from the original feedback.)
* Accuracy: 5 (The answer accurately identifies the positive and negative points mentioned in the original feedback.)
* Relevance: 5 (The answer is directly relevant to the original feedback, as it summarizes the main points.)
* Clarity: 4 (The answer is concise and easy to understand, but it could be improved with more descriptive language and specific examples.)

Total score: 17/20

Here are three improvement suggestions:

1. **Provide more specific examples**: The answer could be improved by including specific quotes or phrases from the original feedback to support the positive and negative points. For example, "The customer liked the app interface, citing its ease of use, and the speed of checkout, but experienced issues with the payment page failing twice."
2. **Include more detail about the sentiment**: While the answer correctly identifies the sentiment as "Neutral", it could be improved by providing more context about why the sentiment is neutral. For example, "The sentiment is neutral because although the customer experienced some negative issues, such as the payment page failing and slow customer support, they were also pleased with the discounts and product quality."
3. **Offer more analysis or insights**: The answer could be improved by providing more analysis or insights about the original feedback. For example, "The customer's experience highlights the importance of reliable payment processing and prompt customer support, but also suggests that attractive discounts can help to offset some negative experiences."
========================================================================================================================

In [34]:
def build_feedback_prompt(feedback, task_type="summary"):
    templates = {
        "summary": f"Summarize the following feedback in 3 bullet points:\n{feedback}",
        "sentiment": f"Identify sentiment and explain why:\n{feedback}",
        "action_items": f"Read the feedback and propose action items:\n{feedback}",
        "json_extract": f"""
Extract issues from this feedback and return JSON with:
payment_issue, support_issue, delivery_issue, packaging_issue, sentiment

Feedback:
{feedback}
"""
    }
    return templates.get(task_type, templates["summary"])

In [35]:
for task in ["summary", "sentiment", "action_items", "json_extract"]:
    p = build_feedback_prompt(customer_feedback, task)
    r = ask_groq(p)
    show_result(f"Prompt Template: {task}", p, r)

========================================================================================================================
TECHNIQUE: Prompt Template: summary
------------------------------------------------------------------------------------------------------------------------
PROMPT:
Summarize the following feedback in 3 bullet points:  I liked the app interface and the speed of checkout.
However, the payment page failed twice before succeeding. Customer support replied after 2 days, which is too
slow. Product quality was good overall, but delivery packaging was damaged. I may still recommend it because
the discounts were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are 3 bullet points summarizing the feedback:

* The app interface was liked, and checkout was fast, but the payment page experienced technical issues.
* Customer support response time was slow, taking 2 days to reply, and the delivery packaging was damaged.
* Despite some issues, the customer might still recommend the app due to attractive discounts and overall good product quality.
========================================================================================================================
========================================================================================================================
TECHNIQUE: Prompt Template: sentiment
------------------------------------------------------------------------------------------------------------------------
PROMPT:
Identify sentiment and explain why:  I liked the app interface and the speed of checkout. However, the payment
page failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product quality
was good overall, but delivery packaging was damaged. I may still recommend it because the discounts were
attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
The overall sentiment of this review is mixed, but leaning towards being slightly negative.

Here's why:

* The customer mentions some positive aspects, such as:
	+ Liking the app interface and checkout speed
	+ Good product quality
	+ Attractive discounts
* However, they also mention several negative experiences, including:
	+ Technical issues with the payment page
	+ Slow customer support response time (2 days)
	+ Damaged delivery packaging
* The customer's tone is not extremely negative, but rather matter-of-fact, listing both the positives and negatives of their experience.
* The fact that they say they "may still recommend" the app suggests that the positive aspects are somewhat outweighed by the negative experiences, but not entirely.
* The use of phrases like "However" and "which is too slow" indicates a sense of disappointment and frustration, which contributes to the slightly negative overall sentiment.

Overall, the customer's experience was not entirely satisfactory, and while they found some aspects of the app and product to be good, the technical issues, slow customer support, and damaged packaging left a negative impression.
========================================================================================================================
========================================================================================================================
TECHNIQUE: Prompt Template: action_items
------------------------------------------------------------------------------------------------------------------------
PROMPT:
Read the feedback and propose action items:  I liked the app interface and the speed of checkout. However, the
payment page failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product
quality was good overall, but delivery packaging was damaged. I may still recommend it because the discounts
were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Based on the customer's feedback, here are some proposed action items:

1. **Improve Payment Page Stability**: Investigate and resolve the issue with the payment page to prevent failures and ensure a seamless checkout experience for customers.
2. **Enhance Customer Support Response Time**: Review and optimize the customer support process to reduce response time, aiming for a faster turnaround, such as responding within 24 hours or less.
3. **Inspect and Improve Delivery Packaging**: Examine the packaging process to prevent damage during shipping and ensure that products arrive in good condition. Consider using more robust packaging materials or redesigning the packaging to better protect the products.
4. **Maintain Competitive Discounts and Promotions**: Continue to offer attractive discounts and promotions to incentivize customers to make purchases and recommend the app to others.
5. **Conduct Follow-up with Customers**: Consider sending a follow-up survey or email to customers who have experienced issues, such as payment failures or damaged packaging, to ensure that their concerns have been addressed and to gather further feedback.

By addressing these areas, the company can improve the overall customer experience, increase customer satisfaction, and encourage positive word-of-mouth recommendations.
========================================================================================================================
========================================================================================================================
TECHNIQUE: Prompt Template: json_extract
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 Extract issues from this feedback and return JSON with: payment_issue, support_issue, delivery_issue,
packaging_issue, sentiment  Feedback:  I liked the app interface and the speed of checkout. However, the
payment page failed twice before succeeding. Customer support replied after 2 days, which is too slow. Product
quality was good overall, but delivery packaging was damaged. I may still recommend it because the discounts
were attractive.
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
Here are the extracted issues in JSON format:

```json
{
  "payment_issue": true,
  "support_issue": true,
  "delivery_issue": false,
  "packaging_issue": true,
  "sentiment": "neutral"
}
```

Explanation:
- `payment_issue`: True, because the payment page failed twice before succeeding.
- `support_issue`: True, because customer support replied after 2 days, which is considered slow.
- `delivery_issue`: False, because there's no mention of a problem with the delivery itself, only the packaging.
- `packaging_issue`: True, because the delivery packaging was damaged.
- `sentiment`: Neutral, because the customer had both positive (liked the app interface, speed of checkout, product quality, and discounts) and negative (payment, support, and packaging issues) experiences, and is still considering recommending the service.
========================================================================================================================

In [36]:
comparison_prompts = {
    "zero_shot": f"Analyze the sentiment of this feedback:\n{customer_feedback}",
    "role_based": f"You are a CX manager. Analyze sentiment and business risks:\n{customer_feedback}",
    "json_output": f"""
Return JSON with sentiment, positives, negatives for:
{customer_feedback}
""",
    "few_shot": f"""
Example:
Feedback: Delivery was late but the product was good.
Sentiment: Neutral

Now analyze:
{customer_feedback}
"""
}

results = []
for name, pr in comparison_prompts.items():
    out = ask_groq(pr)
    results.append({"prompt_type": name, "response_preview": out[:300]})

comparison_df = pd.DataFrame(results)
comparison_df

   prompt_type                                   response_preview
0    zero_shot  The sentiment of this feedback is mixed, but o...
1   role_based  **Sentiment Analysis:**\nThe customer's sentim...
2  json_output  Here is the JSON output with sentiment, positi...
3     few_shot  Feedback: The customer had mixed experiences w...

In [37]:
capstone_text = """
A retail company has collected 500 customer reviews from app, email, and support tickets.
Management wants:
1. top complaint categories,
2. overall sentiment,
3. urgent operational issues,
4. a concise weekly CX report.
"""
print(capstone_text)

A retail company has collected 500 customer reviews from app, email, and support tickets.
Management wants:
1. top complaint categories,
2. overall sentiment,
3. urgent operational issues,
4. a concise weekly CX report.

In [38]:
prompt_capstone = f"""
You are a Lead Customer Experience Analyst.

Problem:
{capstone_text}

Using the sample feedback below as if it were part of the weekly dataset:
{customer_feedback}

Prepare a weekly CX insight report with:
1. Top issues
2. Positive themes
3. Risk areas
4. Immediate actions
5. Suggested dashboard KPIs
"""
response_capstone = ask_groq(prompt_capstone)
show_result("Capstone Prompt Engineering Exercise", prompt_capstone, response_capstone)

========================================================================================================================
TECHNIQUE: Capstone Prompt Engineering Exercise
------------------------------------------------------------------------------------------------------------------------
PROMPT:
 You are a Lead Customer Experience Analyst.  Problem:  A retail company has collected 500 customer reviews
from app, email, and support tickets. Management wants: 1. top complaint categories, 2. overall sentiment, 3.
urgent operational issues, 4. a concise weekly CX report.   Using the sample feedback below as if it were part
of the weekly dataset:  I liked the app interface and the speed of checkout. However, the payment page failed
twice before succeeding. Customer support replied after 2 days, which is too slow. Product quality was good
overall, but delivery packaging was damaged. I may still recommend it because the discounts were attractive.
Prepare a weekly CX insight report with: 1. Top issues 2. Positive themes 3. Risk areas 4. Immediate actions
5. Suggested dashboard KPIs
------------------------------------------------------------------------------------------------------------------------
MODEL RESPONSE:
**Weekly CX Insight Report**

**1. Top Issues:**
Based on the sample feedback, the top complaint categories are:
	* Payment processing issues (payment page failed twice)
	* Slow customer support response time (replied after 2 days)
	* Damaged delivery packaging

These issues are likely to be prevalent across the 500 customer reviews and require attention to improve the overall customer experience.

**2. Positive Themes:**
The customer appreciated:
	* The app interface and speed of checkout
	* Attractive discounts
	* Good product quality

These positive themes can be built upon to enhance the customer experience and increase loyalty.

**3. Risk Areas:**
The risk areas identified are:
	* Payment processing issues, which can lead to abandoned carts and lost sales
	* Slow customer support response time, which can lead to frustrated customers and negative word-of-mouth
	* Damaged delivery packaging, which can lead to product damage and returns

These risk areas require immediate attention to mitigate potential losses and reputation damage.

**4. Immediate Actions:**
To address the top issues and risk areas, the following immediate actions are recommended:
	* Investigate and resolve the payment processing issues to prevent further failures
	* Implement a faster customer support response time, aiming for a response within 24 hours
	* Review and improve the delivery packaging process to prevent damage during transit

**5. Suggested Dashboard KPIs:**
To monitor the customer experience and track improvements, the following dashboard KPIs are suggested:
	* Customer Satisfaction (CSAT) score
	* Net Promoter Score (NPS)
	* First Response Time (FRT) for customer support
	* Payment Processing Success Rate
	* Delivery Packaging Damage Rate
	* App Interface and Checkout Speed metrics (e.g., time to complete checkout, app crash rate)

These KPIs will provide a comprehensive view of the customer experience and help identify areas for improvement.

**Weekly CX Report Template:**
To provide a concise weekly CX report, the following template can be used:

| Category | Metric | Current Value | Target Value | Change |
| --- | --- | --- | --- | --- |
| CSAT | % |  | 85% |  |
| NPS | Score |  | 30 |  |
| FRT | Hours |  | 2 hours |  |
| Payment Processing Success Rate | % |  | 99% |  |
| Delivery Packaging Damage Rate | % |  | 1% |  |

This template can be updated weekly to track progress and identify areas for improvement.
========================================================================================================================

In [39]:
def analyze_feedback_row(feedback):
    prompt = f"""
Analyze this customer feedback and return JSON with:
- sentiment
- positives
- negatives
- main_issue_category

Feedback:
{feedback}
"""
    return ask_groq(prompt)

df["llm_analysis"] = df["feedback"].apply(analyze_feedback_row)
df

,feedback_id,feedback,llm_analysis
0,101,"Checkout was fast and the UI is clean, but pay...","```json\n{\n ""sentiment"": ""neutral"",\n ""posi..."
1,102,"Good product quality, nice discount, but damag...",Here's the analysis of the customer feedback i...
2,103,The app is intuitive and easy to use. Customer...,"```json\n{\n ""sentiment"": ""positive"",\n ""pos..."

In [40]:
reflection_questions = [
    "Which prompting technique gave the most structured output?",
    "Which prompt reduced hallucination risk the most?",
    "Which technique is best for analytics pipelines?",
    "Which technique is best for chatbots?",
    "How did output quality change from zero-shot to few-shot?",
    "When should prompt chaining be preferred over one big prompt?"
]

for i, q in enumerate(reflection_questions, 1):
    print(f"{i}. {q}")

1. Which prompting technique gave the most structured output?
2. Which prompt reduced hallucination risk the most?
3. Which technique is best for analytics pipelines?
4. Which technique is best for chatbots?
5. How did output quality change from zero-shot to few-shot?
6. When should prompt chaining be preferred over one big prompt?